### ISSUE TITLE
Consider providing a way to relax timeout.

### ISSUE THREAD

**Issue by porterjamesj** [roryk/ipython-cluster-helper#16]
When I start up a reasonably large cluster (~300-500 ipengines), my nodes often take forever to come up. [The 60 second timeout](https://github.com/roryk/ipython-cluster-helper/blob/master/cluster_helper/cluster.py#L66) makes this an error, but if I manually relax the timeout everything works fine (eventually). Maybe we could provide a way to do this in the API and expose it from bcbio-nextgen? I would do it myself but I'm not sure what y'all would want the interface to look like; I'm also not caught up with all the latest changes to the bcbio-nextgen parallel code.

**Comment by roryk** [comment]
Closing this out since it is pretty stale. Feel free to reopen if you ended up having some suggestions. Thanks again, hope everything is well James.
