### ISSUE TITLE
leverage content in pyina, and vice-versa

### ISSUE THREAD

**Issue by mmckerns** [roryk/ipython-cluster-helper#17]
pyina has some schedulers and whatnot supported that ipython_cluster_helper doesn't and vice-versa.  https://github.com/uqfoundation/pyina/blob/master/pyina/launchers.py
I also have some machine-specific configs that I keep in a dev branch in my svn.

Both packages are small… we should figure out how to better leverage each other, or at the very least steal from each other mercilessly.  This is on my agenda before summer, depending on proposal and travel commitments.  I'm at the labs all of the time.  Or maybe you guys will be sprinting somewhere I'm attending?  Feel free to send email or otherwise.  I know I've brought this up before, but we should do it.

**Comment by roryk** [comment]
Hi Mike, looks like this isn't going to happen, so closing it out. Totally happy to reopen later on. Thanks so much!

**Comment by mmckerns** [comment]
@roryk: Good move. Hopefully someone becomes annoyed enough to move it off the back burner at some point.  Thanks guys, I'll keep an eyeball on your development until then.
