### ISSUE TITLE
`direct` argument ignored in `cluster_view`

### ISSUE THREAD

**Issue by peteut** [roryk/ipython-cluster-helper#41]
The `direct` argument from `cluster_view` is ignore, [4dd8de8](https://github.com/roryk/ipython-cluster-helper/commit/4dd8de86d46c6a8c123d81ec4e872da51f6aaa2d) should fix it.

**Comment by chapmanb** [comment]
Thanks for the heads up and the fix. Would you be able to submit this as a PR and we can pull it in?

**Comment by roryk** [comment]
How did you make that commit? I just spent 20 minutes trying to figure it out but I'm stuck.

**Comment by peteut** [comment]
Sorry for confusion, I'll prepare a PR for it.

**Comment by roryk** [comment]
Thanks-- it took me a while but I eventually figured out that the repository was deleted after the commit was made.
