### ISSUE TITLE
cluster_helper/lsf.py in a separate package with less/no dependencies?

### ISSUE THREAD

**Issue by mr-c** [roryk/ipython-cluster-helper#52]
As I am about to copy it into https://github.com/BD2KGenomics/toil/ but that seems silly

**Comment by roryk** [comment]
Hi Michael,

Copying it over sounds ok to me, we do most of our installs via conda so it would be a little bit of a pain to make a new package and all of that for it. Let me know if copying it over is a pain for you all and I can break it out though. Hope that works for you all.

**Comment by mr-c** [comment]
@roryk Done, thanks! https://github.com/BD2KGenomics/toil/pull/1762
