### ISSUE TITLE
Can bcbio_nextgen run via ipython parallel on an SGE cluster where the qsub command can't be executed from the compute nodes?

### ISSUE THREAD

**Issue by amizeranschi** [roryk/ipython-cluster-helper#62]
Hello,

Is there any chance to run bcbio_nextgen run via ipython parallel on an SGE cluster where the qsub command can't be executed from the compute nodes? I posted more information about this on the bcbio_nextgen issue tracker: https://github.com/bcbio/bcbio-nextgen/issues/2701.

**Comment by roryk** [comment]
Hi @amizeranschi, for this case, you'll have to run the main `bcbio_nextgen.py` job from the login node. The `bcbio_nextgen.py` job is the one that does the submission to the queue, so all of those jobs should get submitted via the login node if you run it there.

**Comment by amizeranschi** [comment]
Thanks for your reply. I'm having some trouble also when running `bcbio_nextgen.py` from the login node. The sge_controller and sge_engine are starting up, but don't seem to be communicating properly. I posted more info on the bcbio_nextgen issue tracker.

**Comment by amizeranschi** [comment]
Just to clarify, when you mean `run the main bcbio_nextgen.py job from the login node`, do you mean it has to be run via qsub (via the SGE queue), but it should then get executed on the login node instead of a compute node? Or do you mean that the script which invokes `bcbio_nextgen.py` should be run directly via Bash, on the login node?

**Comment by roryk** [comment]
Hi @amizeranschi,

Sorry for not being clear. The latter is right, just calling it from bash.
